import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API = 'https://openlibrary.org/search.json?q=';
const starterBooks = [
  { key: '/works/OL45804W', title: 'The Little Prince', author_name: ['Antoine de Saint-Exupéry'], first_publish_year: 1943, cover_i: 8231856 },
  { key: '/works/OL7353617W', title: 'Atomic Habits', author_name: ['James Clear'], first_publish_year: 2018, cover_i: 12640549 },
  { key: '/works/OL27448W', title: 'Pride and Prejudice', author_name: ['Jane Austen'], first_publish_year: 1813, cover_i: 8091016 }
];
const cover = id => id ? `https://covers.openlibrary.org/b/id/${id}-M.jpg` : 'https://placehold.co/120x180/e0e7ff/4338ca?text=Book';

function App() {
  const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('bookfinder-user') || 'null'));
  const [page, setPage] = useState('home'); const [selected, setSelected] = useState(null); const [menu, setMenu] = useState(false);
  const [favorites, setFavorites] = useState(() => JSON.parse(localStorage.getItem('bookfinder-favorites') || '[]'));
  const [query, setQuery] = useState(''); const [books, setBooks] = useState(starterBooks); const [loading, setLoading] = useState(false); const [notice, setNotice] = useState('');
  useEffect(() => localStorage.setItem('bookfinder-favorites', JSON.stringify(favorites)), [favorites]);
  useEffect(() => { if (notice) { const t = setTimeout(() => setNotice(''), 3000); return () => clearTimeout(t); } }, [notice]);
  const go = p => { setPage(p); setMenu(false); setSelected(null); };
  const search = async e => { e.preventDefault(); if (!query.trim()) return; setLoading(true); try { const r = await fetch(API + encodeURIComponent(query)); const d = await r.json(); setBooks(d.docs.slice(0, 8)); setNotice(`Loaded ${d.numFound.toLocaleString()} results from Open Library`); } catch { setNotice('Could not reach the API. Showing sample books.'); } finally { setLoading(false); } };
  const toggleFavorite = b => setFavorites(f => f.some(x => x.key === b.key) ? f.filter(x => x.key !== b.key) : [...f, b]);
  if (!user) return <Auth onLogin={u => { setUser(u); localStorage.setItem('bookfinder-user', JSON.stringify(u)); }} />;
  return <div className="app"><header><button className="brand" onClick={() => go('home')}>📚 Book Finder</button><nav><button onClick={() => go('home')}>Home</button><button onClick={() => go('favorites')}>Favorites ({favorites.length})</button><button onClick={() => go('profile')}>Profile</button><button className="menuButton" aria-label="Open settings menu" onClick={() => setMenu(!menu)}>☰</button></nav>{menu && <div className="menu"><button onClick={() => go('settings')}>⚙ Settings</button><button onClick={() => { setNotice('You have no new notifications'); setMenu(false); }}>🔔 Notifications</button><button onClick={() => { localStorage.clear(); location.reload(); }}>↪ Log out</button></div>}</header>{notice && <div className="toast" role="status">{notice}</div>}
    {page === 'home' && <main><section className="hero"><p className="eyebrow">DISCOVER YOUR NEXT STORY</p><h1>Find a book<br /><span>you’ll love.</span></h1><p>Search millions of books and save your favorites in one friendly place.</p><form onSubmit={search}><input aria-label="Search books" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search by title or author" /><button className="primary">{loading ? 'Searching…' : 'Search'}</button></form></section><BookGrid books={books} favorites={favorites} onSelect={b => { setSelected(b); setPage('detail'); }} onFavorite={toggleFavorite} /></main>}
    {page === 'favorites' && <main className="content"><h2>Your favorites</h2><p className="muted">Saved in your browser with local storage.</p>{favorites.length ? <BookGrid books={favorites} favorites={favorites} onSelect={b => { setSelected(b); setPage('detail'); }} onFavorite={toggleFavorite} /> : <Empty text="No favorites yet. Tap the heart on a book to save it." />}</main>}
    {page === 'detail' && <main className="content"><button className="back" onClick={() => go('home')}>← Back to books</button><article className="detail"><img src={cover(selected.cover_i)} /><div><p className="eyebrow">BOOK DETAILS</p><h2>{selected.title}</h2><h3>by {(selected.author_name || ['Unknown author']).join(', ')}</h3><p>First published in {selected.first_publish_year || 'an unknown year'}. Explore this title through the Open Library search API.</p><button className="primary" onClick={() => toggleFavorite(selected)}>{favorites.some(x => x.key === selected.key) ? '♥ Saved' : '♡ Add to favorites'}</button></div></article></main>}
    {page === 'profile' && <main className="content"><h2>Your profile</h2><div className="profile"><div className="avatar">{user.name[0].toUpperCase()}</div><h3>{user.name}</h3><p>{user.email}</p><p className="muted">{favorites.length} saved book{favorites.length === 1 ? '' : 's'}</p></div></main>}
    {page === 'settings' && <main className="content"><h2>Settings</h2><div className="settings"><label>Display name<input value={user.name} onChange={e => { const u={...user,name:e.target.value}; setUser(u); localStorage.setItem('bookfinder-user',JSON.stringify(u)); }} /></label><label className="switch"><input type="checkbox" defaultChecked /> Email reading recommendations</label><button className="primary" onClick={() => setNotice('Settings saved successfully')}>Save settings</button><hr /><h3>Browser notifications</h3><p className="muted">Allow notifications, then send a test message to capture your evidence.</p><button onClick={async () => { if (!('Notification' in window)) return setNotice('Notifications are not supported in this browser'); const permission = await Notification.requestPermission(); if (permission === 'granted') { new Notification('Book Finder', { body: 'Your reading list is ready!' }); setNotice('Test notification sent'); } else setNotice('Notification permission was not granted'); }}>Enable & test notification</button></div></main>}
  </div>;
}
function BookGrid({ books, favorites, onSelect, onFavorite }) { return <section className="grid">{books.map((b, i) => <article className="card" key={b.key || i}><button className="coverButton" onClick={() => onSelect(b)}><img src={cover(b.cover_i)} alt={`Cover of ${b.title}`} /></button><div className="cardBody"><button className="heart" aria-label="Toggle favorite" onClick={() => onFavorite(b)}>{favorites.some(x => x.key === b.key) ? '♥' : '♡'}</button><h3>{b.title}</h3><p>{(b.author_name || ['Unknown author'])[0]}</p><small>{b.first_publish_year || '—'}</small></div></article>)}</section>; }
function Empty({ text }) { return <div className="empty">{text}</div>; }
function Auth({ onLogin }) { const [mode,setMode]=useState('signup'); const [form,setForm]=useState({name:'',email:'',password:''}); const [error,setError]=useState(''); const submit=e=>{e.preventDefault(); if(mode==='signup'&&!form.name.trim()) return setError('Please enter your name.'); if(!/^\S+@\S+\.\S+$/.test(form.email)) return setError('Please enter a valid email address.'); if(form.password.length<6) return setError('Password must be at least 6 characters.'); onLogin({name:form.name||form.email.split('@')[0],email:form.email});}; return <div className="auth"><div className="authCard"><div className="logo">📚</div><p className="eyebrow">WELCOME TO</p><h1>Book Finder</h1><p className="muted">{mode==='signup'?'Create an account to save your reads.':'Log in to continue your reading journey.'}</p><form onSubmit={submit}>{mode==='signup'&&<input aria-label="Full name" placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/>}<input aria-label="Email" type="email" placeholder="Email address" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input aria-label="Password" type="password" placeholder="Password (6+ characters)" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>{error&&<p className="error" role="alert">{error}</p>}<button className="primary">{mode==='signup'?'Create account':'Log in'}</button></form><button className="link" onClick={()=>{setMode(mode==='signup'?'login':'signup');setError('')}}>{mode==='signup'?'Already have an account? Log in':'Need an account? Sign up'}</button></div></div>; }
createRoot(document.getElementById('root')).render(<App />);
